export const PageLayoutConstants = {
    HEADER_HEIGHT: 50,
    FOOTER_HEIGHT: 120,
    CONTENT_BACKGROUND_HORIZONTAL_MARGIN: 100,
    CONTENT_WIDTH: 800
}

export const PageLayoutConstantsMobile = {
    HEADER_HEIGHT: 50,
    FOOTER_HEIGHT: 120,
    CONTENT_BACKGROUND_HORIZONTAL_MARGIN: 100,
    CONTENT_WIDTH: 300,
    SECTION_CONTENT_SIDE_MARGIN: 40,
}